# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  
  config.vm.define "mgmt-svr" do |cfg|
    cfg.vm.box = "bento/ubuntu-20.04"
    cfg.vm.network "private_network", ip: "192.168.56.1"
    cfg.vm.network "forwarded_port", guest: 22, host: 60005, auto_correct: true, id: "ssh"
    cfg.vm.hostname = "mgmt-svr"
    cfg.vm.provider "virtualbox" do |vb|
      vb.memory = 2048
      vb.cpus = 2
      vb.gui = false
    end
    cfg.vm.provision "shell", path: "change-ubuntu-mirror.sh"
    cfg.vm.provision "shell", path: "install.sh"
  end

end